### ISSUE TITLE
Does your firmware work with Creality Original Upgrade Ender 3 V2 Intelligent Screen Kit HD Color Screen Display Compatible with Ender-3 V2, Ender 3 pro, Ender 3 D Printer

### ISSUE THREAD

**Issue by FUEL4EP** [Jimsterdelux13/ender3-s1-pro-marlin2.1.x-firmware#1]
Hi,

Does your firmware work with Creality Original Upgrade Ender 3 V2 Intelligent Screen Kit HD Color Screen Display Compatible with Ender-3 V2, Ender 3 pro, Ender 3 D Printer, e.g. from [here](https://www.amazon.de/Creality-Original-Upgrade-Intelligent-kompatibel/dp/B09292H22C)?

**Comment by Jimsterdelux13** [comment]
This firmware is set up only for the Creality V24S1_301 Board with the F4 CPU and 12864 creality display.
